remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Green Computing in Research
description: This site contains induction and training materials for sustainable computing best practice at the University of Exeter 
